/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type SocialMediaPlatform = 'LINKEDIN' | 'FACEBOOK' | 'INSTAGRAM' | 'SNAPCHAT' | 'WHATSAPP';

export const SocialMediaPlatform = {
    Linkedin: 'LINKEDIN' as SocialMediaPlatform,
    Facebook: 'FACEBOOK' as SocialMediaPlatform,
    Instagram: 'INSTAGRAM' as SocialMediaPlatform,
    Snapchat: 'SNAPCHAT' as SocialMediaPlatform,
    Whatsapp: 'WHATSAPP' as SocialMediaPlatform
};

